In [2]:
import pandas as pd

In [9]:
CSV_PATH = r"C:\Users\Parveen\Desktop\python_projects\python_series\python_practise\employees.csv"

df = pd.read_csv(CSV_PATH)
df

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,day,temp,condition
0,0,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,3152.00,6304.0,56736.0,0.0,0.0,NaN,NaN,0,NaN
1,1,20,Justin Robinson,43,jadkins@example.com,Civil,97079,East Ericchester,4853.95,9707.9,87371.1,0.0,0.0,NaN,NaN,0,NaN
2,2,10,Mary Hoover,29,khernandez@example.com,Civil,90623,Port Thomasfurt,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
3,3,24,Heather Bailey,23,harrisedward@example.org,Civil,37738,Kristyview,1886.90,3773.8,33964.2,0.0,0.0,NaN,NaN,0,NaN
4,4,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
5,5,28,Hannah Reed,34,brandi23@example.org,Civil,87249,New Susan,4362.45,8724.9,78524.1,0.0,0.0,NaN,NaN,0,NaN
6,6,7,Craig Lewis,22,matthew34@example.net,Civil,34322,Christophermouth,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
7,7,4,Paul Andrews,25,whitemichael@example.com,Civil,95395,Lake Robertfurt,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
8,8,21,Taylor Kerr,54,hughesdeborah@example.net,Civil,65482,Port Amandabury,3274.10,6548.2,58933.8,0.0,0.0,NaN,NaN,0,NaN
9,9,10,Mary Hoover,29,khernandez@example.com,Civil,90623,Port Thomasfurt,4531.15,9062.3,81560.7,0.0,0.0,NaN,NaN,0,NaN
10,10,22,Jared Ferguson,32,sandra38@example.com,Civil,81867,West Amanda,4093.35,8186.7,73680.3,0.0,0.0,NaN,NaN,0,NaN
11,11,20,Justin Robinson,43,jadkins@example.com,Civil,97079,East Ericchester,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
12,12,7,Craig Lewis,22,matthew34@example.net,Civil,34322,Christophermouth,1716.10,3432.2,30889.8,0.0,0.0,NaN,NaN,0,NaN
13,13,21,Taylor Kerr,54,hughesdeborah@example.net,Civil,65482,Port Amandabury,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
14,14,22,Jared Ferguson,32,sandra38@example.com,Civil,81867,West Amanda,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
15,15,4,Paul Andrews,25,whitemichael@example.com,Civil,95395,Lake Robertfurt,4769.75,9539.5,85855.5,0.0,0.0,NaN,NaN,0,NaN
16,16,24,Heather Bailey,23,harrisedward@example.org,Civil,37738,Kristyview,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
17,17,28,Hannah Reed,34,brandi23@example.org,Civil,87249,New Susan,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
18,18,23,Stephanie Murray,23,terri73@example.net,Electrical,49030,Kristyport,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
19,19,11,Todd Clark,21,williamwilliams@example.net,Electrical,77005,Amandaport,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
20,20,23,Stephanie Murray,23,terri73@example.net,Electrical,49030,Kristyport,2451.50,4903.0,44127.0,0.0,0.0,NaN,NaN,0,NaN
21,21,11,Todd Clark,21,williamwilliams@example.net,Electrical,77005,Amandaport,3850.25,7700.5,69304.5,0.0,0.0,NaN,NaN,0,NaN
22,22,3,Kendra Cunningham,20,terri73@example.org,IT,64085,East Kevintown,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
23,23,1,Randall Sharp,22,khernandez@example.net,IT,73958,Kellymouth,3697.90,7395.8,66562.2,0.0,0.0,NaN,NaN,0,NaN
24,24,12,Sarah Bell,20,stephanie57@example.org,IT,88955,South Leahshire,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
25,25,16,Tina Washington,22,josephkennedy@example.com,IT,97535,Lake Amberfort,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
26,26,18,Brent Lambert,54,khernandez@example.org,IT,98386,West Danielchester,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
27,27,19,Patricia Hoover,23,rhodessarah@example.com,IT,36021,Matthewbury,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
28,28,8,Paul Hawkins,21,fyoung@example.org,IT,41079,Michaelview,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
29,29,1,Randall Sharp,22,khernandez@example.net,IT,73958,Kellymouth,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
30,30,30,Veronica Jones,21,khernandez@example.com,IT,99244,North Isaac,4962.20,9924.4,89319.6,0.0,0.0,NaN,NaN,0,NaN
31,31,30,Veronica Jones,21,khernandez@example.com,IT,99244,North Isaac,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
32,32,3,Kendra Cunningham,20,terri73@example.org,IT,64085,East Kevintown,3204.25,6408.5,57676.5,0.0,0.0,NaN,NaN,0,NaN
33,33,19,Patricia Hoover,23,rhodessarah@example.com,IT,36021,Matthewbury,1801.05,3602.1,32418.9,0.0,0.0,NaN,NaN,0,NaN
34,34,18,Brent Lambert,54,khernandez@example.org,IT,98386,West Danielchester,4919.30,9838.6,88547.4,0.0,0.0,NaN,NaN,0,NaN
35,35,8,Paul Hawkins,21,fyoung@example.org,IT,41079,Michaelview,2053.95,4107.9,36971.1,0.0,0.0,NaN,NaN,0,NaN
36,36,16,Tina Washington,22,josephkennedy@example.com,IT,97535,Lake Amberfort,4876.75,9753.5,87781.5,0.0,0.0,NaN,NaN,0,NaN
37,37,12,Sarah Bell,20,stephanie57@example.org,IT,88955,South Leahshire,4447.75,8895.5,80059.5,0.0,0.0,NaN,NaN,0,NaN
38,38,2,Charles Wheeler,30,chad73@example.org,Marketing,81047,Robinsonbury,4052.35,8104.7,72942.3,0.0,0.0,NaN,NaN,0,NaN
39,39,27,Elizabeth Webb,21,josephking@example.com,Marketing,32192,Fritzview,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
40,40,26,Mark Peters,61,zcompton@example.com,Marketing,62268,Davidhaven,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
41,41,25,Karen Morales,45,cowanmatthew@example.com,Marketing,35814,Cabreraside,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
42,42,6,Steven Mason,30,antonioporter@example.net,Marketing,79606,Molinaberg,3980.30,7960.6,71645.4,0.0,0.0,NaN,NaN,0,NaN
43,43,17,Richard Avila,34,desiree24@example.net,Marketing,85185,Jamesborough,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
44,44,15,Johnny Roy,10,brooksrodney@example.org,Marketing,84243,Madisonberg,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
45,45,15,Johnny Roy,10,brooksrodney@example.org,Marketing,84243,Madisonberg,4212.15,8424.3,75818.7,0.0,0.0,NaN,NaN,0,NaN
46,46,17,Richard Avila,34,desiree24@example.net,Marketing,85185,Jamesborough,4259.25,8518.5,76666.5,0.0,0.0,NaN,NaN,0,NaN
47,47,25,Karen Morales,45,cowanmatthew@example.com,Marketing,35814,Cabreraside,1790.70,3581.4,32232.6,0.0,0.0,NaN,NaN,0,NaN
48,48,6,Steven Mason,30,antonioporter@example.net,Marketing,79606,Molinaberg,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
49,49,26,Mark Peters,61,zcompton@example.com,Marketing,62268,Davidhaven,3113.40,6226.8,56041.2,0.0,0.0,NaN,NaN,0,NaN
50,50,27,Elizabeth Webb,21,josephking@example.com,Marketing,32192,Fritzview,1609.60,3219.2,28972.8,0.0,0.0,NaN,NaN,0,NaN
51,51,2,Charles Wheeler,30,chad73@example.org,Marketing,81047,Robinsonbury,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
52,52,13,Rebecca Merritt,21,carlysmith@example.org,Mechanical,69818,South Sabrina,3490.90,6981.8,62836.2,0.0,0.0,NaN,NaN,0,NaN
53,53,13,Rebecca Merritt,21,carlysmith@example.org,Mechanical,69818,South Sabrina,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
54,54,9,Frank Johnson,19,sandymatthews@example.net,Mechanical,63935,Port Christopher,3196.75,6393.5,57541.5,0.0,0.0,NaN,NaN,0,NaN
55,55,9,Frank Johnson,19,sandymatthews@example.net,Mechanical,63935,Port Christopher,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
56,56,5,Heather Estrada,44,joelho@example.net,Mechanical,76673,Micheleshire,3833.65,7667.3,69005.7,0.0,0.0,NaN,NaN,0,NaN
57,57,5,Heather Estrada,44,joelho@example.net,Mechanical,76673,Micheleshire,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
58,58,29,Patrick Lewis,20,tneal@example.org,Mechanical,39095,Debbieshire,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
59,59,29,Patrick Lewis,20,tneal@example.org,Mechanical,39095,Debbieshire,1954.75,3909.5,35185.5,0.0,0.0,NaN,NaN,0,NaN

In [ ]:
# give the first 5 rows and if we provide value so it give that range of rows
df.head()
# df.head(10)

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,day,temp,condition
0,0,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,3152.00,6304.0,56736.0,0.0,0.0,NaN,NaN,0,NaN
1,1,20,Justin Robinson,43,jadkins@example.com,Civil,97079,East Ericchester,4853.95,9707.9,87371.1,0.0,0.0,NaN,NaN,0,NaN
2,2,10,Mary Hoover,29,khernandez@example.com,Civil,90623,Port Thomasfurt,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
3,3,24,Heather Bailey,23,harrisedward@example.org,Civil,37738,Kristyview,1886.90,3773.8,33964.2,0.0,0.0,NaN,NaN,0,NaN
4,4,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN

In [19]:
# it give the last 5 rows (default) and if we provide value so it give those rows
df.tail()
# df.tail(10)

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,day,temp,condition
55,55,9,Frank Johnson,19,sandymatthews@example.net,Mechanical,63935,Port Christopher,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
56,56,5,Heather Estrada,44,joelho@example.net,Mechanical,76673,Micheleshire,3833.65,7667.3,69005.7,0.0,0.0,NaN,NaN,0,NaN
57,57,5,Heather Estrada,44,joelho@example.net,Mechanical,76673,Micheleshire,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
58,58,29,Patrick Lewis,20,tneal@example.org,Mechanical,39095,Debbieshire,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
59,59,29,Patrick Lewis,20,tneal@example.org,Mechanical,39095,Debbieshire,1954.75,3909.5,35185.5,0.0,0.0,NaN,NaN,0,NaN

In [ ]:
# it give all columns name
df.columns

Index(['Unnamed: 0', 'employee_id', 'name', 'age', 'email', 'department',
       'salary', 'city', 'bonus', 'tax', 'net_salary', 'month', 'sales',
       'subjects', 'day', 'temp', 'condition'],
      dtype='object')

In [27]:
# it provide of rows and columns
df.shape

(60, 17)

In [29]:
df.describe()

,Unnamed: 0,employee_id,age,salary,bonus,tax,net_salary,month,sales,subjects,day,temp,condition
count,60.000000,60.000000,60.000000,60.000000,60.000000,30.000000,30.000000,60.0,60.0,0.0,0.0,60.0,0.0
mean,29.500000,15.500000,28.866667,69598.966667,1739.974167,6959.896667,62639.070000,0.0,0.0,NaN,NaN,0.0,NaN
std,17.464249,8.728484,12.150841,21994.349189,1919.248050,2218.314535,19964.830814,0.0,0.0,NaN,NaN,0.0,NaN
min,0.000000,1.000000,10.000000,32192.000000,0.000000,3219.200000,28972.800000,0.0,0.0,NaN,NaN,0.0,NaN
25%,14.750000,8.000000,21.000000,49030.000000,0.000000,5233.950000,47105.550000,0.0,0.0,NaN,NaN,0.0,NaN
50%,29.500000,15.500000,23.000000,75315.500000,804.800000,7531.550000,67783.950000,0.0,0.0,NaN,NaN,0.0,NaN
75%,44.250000,23.000000,34.000000,87249.000000,3731.837500,8673.300000,78059.700000,0.0,0.0,NaN,NaN,0.0,NaN
max,59.000000,30.000000,61.000000,99244.000000,4962.200000,9924.400000,89319.600000,0.0,0.0,NaN,NaN,0.0,NaN

In [32]:
df.dtypes

Unnamed: 0       int64
employee_id      int64
name            object
age              int64
email           object
department      object
salary           int64
city            object
bonus          float64
tax            float64
net_salary     float64
month          float64
sales          float64
subjects       float64
day            float64
temp             int64
condition      float64
dtype: object

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   60 non-null     int64
 1   employee_id  60 non-null     int64
 2   name         60 non-null     object
 3   age          60 non-null     int64
 4   email        60 non-null     object
 5   department   60 non-null     object
 6   salary       60 non-null     int64
 7   city         60 non-null     object
 8   bonus        60 non-null     float64
 9   tax          30 non-null     float64
 10  net_salary   30 non-null     float64
 11  month        60 non-null     float64
 12  sales        60 non-null     float64
 13  subjects     0 non-null      float64
 14  day          0 non-null      float64
 15  temp         60 non-null     int64
 16  condition    0 non-null      float64
dtypes: float64(8), int64(5), object(4)
memory usage: 8.1+ KB

In [40]:
df["name"]

0            Laurie Cox
1       Justin Robinson
2           Mary Hoover
3        Heather Bailey
4            Laurie Cox
5           Hannah Reed
6           Craig Lewis
7          Paul Andrews
8           Taylor Kerr
9           Mary Hoover
10       Jared Ferguson
11      Justin Robinson
12          Craig Lewis
13          Taylor Kerr
14       Jared Ferguson
15         Paul Andrews
16       Heather Bailey
17          Hannah Reed
18     Stephanie Murray
19           Todd Clark
20     Stephanie Murray
21           Todd Clark
22    Kendra Cunningham
23        Randall Sharp
24           Sarah Bell
25      Tina Washington
26        Brent Lambert
27      Patricia Hoover
28         Paul Hawkins
29        Randall Sharp
30       Veronica Jones
31       Veronica Jones
32    Kendra Cunningham
33      Patricia Hoover
34        Brent Lambert
35         Paul Hawkins
36      Tina Washington
37           Sarah Bell
38      Charles Wheeler
39       Elizabeth Webb
40          Mark Peters
41        Karen Morales
42         Steven Mason
43        Richard Avila
44           Johnny Roy
45           Johnny Roy
46        Richard Avila
47        Karen Morales
48         Steven Mason
49          Mark Peters
50       Elizabeth Webb
51      Charles Wheeler
52      Rebecca Merritt
53      Rebecca Merritt
54        Frank Johnson
55        Frank Johnson
56      Heather Estrada
57      Heather Estrada
58        Patrick Lewis
59        Patrick Lewis
Name: name, dtype: object

In [42]:
df[['name','age']]

                 name  age
0          Laurie Cox   22
1     Justin Robinson   43
2         Mary Hoover   29
3      Heather Bailey   23
4          Laurie Cox   22
5         Hannah Reed   34
6         Craig Lewis   22
7        Paul Andrews   25
8         Taylor Kerr   54
9         Mary Hoover   29
10     Jared Ferguson   32
11    Justin Robinson   43
12        Craig Lewis   22
13        Taylor Kerr   54
14     Jared Ferguson   32
15       Paul Andrews   25
16     Heather Bailey   23
17        Hannah Reed   34
18   Stephanie Murray   23
19         Todd Clark   21
20   Stephanie Murray   23
21         Todd Clark   21
22  Kendra Cunningham   20
23      Randall Sharp   22
24         Sarah Bell   20
25    Tina Washington   22
26      Brent Lambert   54
27    Patricia Hoover   23
28       Paul Hawkins   21
29      Randall Sharp   22
30     Veronica Jones   21
31     Veronica Jones   21
32  Kendra Cunningham   20
33    Patricia Hoover   23
34      Brent Lambert   54
35       Paul Hawkins   21
36    Tina Washington   22
37         Sarah Bell   20
38    Charles Wheeler   30
39     Elizabeth Webb   21
40        Mark Peters   61
41      Karen Morales   45
42       Steven Mason   30
43      Richard Avila   34
44         Johnny Roy   10
45         Johnny Roy   10
46      Richard Avila   34
47      Karen Morales   45
48       Steven Mason   30
49        Mark Peters   61
50     Elizabeth Webb   21
51    Charles Wheeler   30
52    Rebecca Merritt   21
53    Rebecca Merritt   21
54      Frank Johnson   19
55      Frank Johnson   19
56    Heather Estrada   44
57    Heather Estrada   44
58      Patrick Lewis   20
59      Patrick Lewis   20

In [44]:
df.loc[0]

Unnamed: 0                       0
employee_id                     14
name                    Laurie Cox
age                             22
email          terri73@example.org
department                   Civil
salary                       63040
city               Jacquelineburgh
bonus                       3152.0
tax                         6304.0
net_salary                 56736.0
month                          0.0
sales                          0.0
subjects                       NaN
day                            NaN
temp                             0
condition                      NaN
Name: 0, dtype: object

In [46]:
df.iloc[2]

Unnamed: 0                          2
employee_id                        10
name                      Mary Hoover
age                                29
email          khernandez@example.com
department                      Civil
salary                          90623
city                  Port Thomasfurt
bonus                             0.0
tax                               NaN
net_salary                        NaN
month                             0.0
sales                             0.0
subjects                          NaN
day                               NaN
temp                                0
condition                         NaN
Name: 2, dtype: object

In [50]:
# slicing using iloc
df.iloc[2:5]

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,day,temp,condition
2,2,10,Mary Hoover,29,khernandez@example.com,Civil,90623,Port Thomasfurt,0.0,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
3,3,24,Heather Bailey,23,harrisedward@example.org,Civil,37738,Kristyview,1886.9,3773.8,33964.2,0.0,0.0,NaN,NaN,0,NaN
4,4,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,0.0,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN

In [52]:
df.loc[1:5,['name','age']]

              name  age
1  Justin Robinson   43
2      Mary Hoover   29
3   Heather Bailey   23
4       Laurie Cox   22
5      Hannah Reed   34

In [61]:
# print how many rows using 3 ways
len(df)
df.index.size
df.shape[0]

60

In [72]:
a = [12,3,4,5,6,7,8,9,10]

# formula
# avg = sum(a) / len(a)

avg = df['salary'].mean()
avg

np.float64(69598.96666666666)

In [85]:
df.columns.to_list()

df.columns[:4].to_list()

['Unnamed: 0', 'employee_id', 'name', 'age']

In [87]:
df.select_dtypes(include='number').columns

Index(['Unnamed: 0', 'employee_id', 'age', 'salary', 'bonus', 'tax',
       'net_salary', 'month', 'sales', 'subjects', 'day', 'temp', 'condition'],
      dtype='object')

In [ ]:
df.loc[df['salary']>90000,['name','salary']]

               name  salary
1   Justin Robinson   97079
2       Mary Hoover   90623
7      Paul Andrews   95395
9       Mary Hoover   90623
11  Justin Robinson   97079
15     Paul Andrews   95395
25  Tina Washington   97535
26    Brent Lambert   98386
30   Veronica Jones   99244
31   Veronica Jones   99244
34    Brent Lambert   98386
36  Tina Washington   97535