In [ ]:
import pandas as pd

In [110]:
CSV_PATH = r"C:\Users\Parveen\Desktop\python_projects\python_series\python_practise\data.csv"

df = pd.read_csv(CSV_PATH)
df

       Name      Age Experience   Salary     Department
0     Belas       23          5    30000             IT
1   Charlie       30          3    35000             HR
2      Kate       25         10    25000   Data Science
3     Alies       32         19    20000      Developer
4     Sunny       29          2    20000          Cloud
5      Paul       20          4    15000        Backend
6     Harsh       21          1    18000             HR
7      Ross      NaN        NaN    40000             IT
8   Missing       32         10    38000   Data Science
9       NaN       24    Missing      NaN  Data Engineer
10     John      NaN          6    28000             IT
11    Sarah       27        NaN  Missing             HR
12      NaN       29          8    32000            NaN
13     Mike  Missing          5    25000      Developer
14    David       26        NaN  Missing          Cloud
15     Emma      NaN        NaN    45000            NaN
16    Sarah       27        NaN  Missing             HR

In [ ]:
# give the first 5 rows and if we provide value so it give that range of rows
df.head()
# df.head(10)

In [ ]:
# it give the last 5 rows (default) and if we provide value so it give those rows
df.tail()
# df.tail(10)

In [ ]:
# it give all columns name
df.columns

In [ ]:
# it provide of rows and columns
df.shape

In [ ]:
df.describe()

In [ ]:
df.dtypes

In [ ]:
df.info()

In [ ]:
df["name"]

In [ ]:
df[['name','age']]

In [ ]:
df.loc[0]

In [ ]:
df.iloc[2]

In [ ]:
# slicing using iloc
df.iloc[2:5]

In [ ]:
df.loc[1:5,['name','age']]

In [ ]:
# print how many rows using 3 ways
len(df)
df.index.size
df.shape[0]

In [ ]:
a = [12,3,4,5,6,7,8,9,10]

# formula
# avg = sum(a) / len(a)

avg = df['salary'].mean()
avg

In [ ]:
df.columns.to_list()

df.columns[:4].to_list()

In [ ]:
df.select_dtypes(include='number').columns

In [ ]:
df.loc[df['salary']>90000,['name','salary']]
df

In [ ]:
# & , | operator, ==
# filter > ,<
# df.rename
# str.upper

# all email uppercase using def func
    # using apply

# and condition (want all true = true )
df[(df['salary'] > 90000) & (df['age']>40)]

# or condition (want 1 true)
df[(df['salary'] > 100000) | (df['age']>40)]


# name columns upper case
df['name'].str.upper()

# columns name upper case
df.columns.str.upper().to_list()

# check the name 
df[df['name'] == 'Laurie Cox']

# rename
df.rename(columns={'Unnamed: 0':'Index','name':'Full Name'})

# replace 
df['name'].replace({'Laurie Cox':'Belas'})

In [ ]:
# Create a DataFrame from a CSV file.

people = {
    'first_name' : ['bleas','charlie','alies'],
    'last_name': ['doe','kate','john'],
    'email' : ['belas@gmail.com','charlie@gmail.com','alies@gmail.com']
}


df = pd.DataFrame(people)
df.to_csv('people.csv')

In [ ]:
# Display the first 5 rows.
df.head()

In [ ]:
# Display the last 10 rows.
df.tail(10)

In [ ]:
# Check the number of rows and columns.
df.shape

In [ ]:
# Check column names.
df.columns

In [ ]:
# Check data types of all columns.
df.dtypes

In [ ]:
# Use describe() on numerical columns.
df.describe()

In [ ]:
# Select one column from a DataFrame.
df['name']

In [ ]:
# Select multiple columns.
df[['name','age']]


# iloc on index 
# loc 

# Select rows using iloc.
# Select rows using loc.
df.iloc[0]
df.loc[0]

In [ ]:
# Filter employees whose salary is greater than 50,000.

df.loc[df['salary'] > 50000]

In [ ]:
# Filter students whose age is between 18 and 25.
df.loc[(df['age']>18) & (df['age'] < 25)]

In [ ]:
# Sort a DataFrame by salary in descending order.
df.sort_values(by='salary',ascending=False)

In [ ]:
df.loc[df['age']>25]

In [ ]:
import pandas as pd

In [ ]:
CSV_PATH_1 = r"C:\Users\Parveen\Desktop\python_projects\python_series\python_practise\data.csv"
df = pd.read_csv(CSV_PATH_1)
df

In [ ]:
df[df['department'] == 'IT']

In [ ]:
sum(df['salary']) / len(df["salary"])
df["salary"].mean(),

In [ ]:
df.loc[df['salary'] > 50000]

In [ ]:
# Filter students whose age is between 18 and 25.
# df.loc[(df['age'] > 18) & (df['age'] < 25)]
df.loc[df['age'].between(18,25)]

In [ ]:
CSV_FILE = r'./employees.csv'
df = pd.read_csv(CSV_FILE)
df.head()

In [ ]:
df.rename(columns={'name':"Full Name"}).head()

In [ ]:
df.loc[df['email'] == "terri73@example.org"]

In [ ]:
df['name'].replace({'Laurie Cox':'John doe'})

In [ ]:
df['yearly_salary'] = df['salary'] * 12
df.head(1)

In [ ]:
# df.drop(columns=['day'],inplace=True)
df.head()

In [ ]:
df[['first_name','last_name']] = df['name'].str.split(' ',expand=True)
df.head(1)

In [ ]:
new_row = pd.DataFrame({
    'name':['Belas Kate'],
    'age':23,
    'salaly':45000
})
df = pd.concat([df,new_row],ignore_index=True)
df

In [ ]:
df.sort_values(by='name',ascending=True)
df.sort_values(by='salary',ascending=False)

In [ ]:
df.sort_index()

In [ ]:
df.sort_values(by='employee_id',ascending=True)

In [ ]:
df.sort_values(by='salary',ascending=False).head(1)

In [ ]:
df

In [ ]:
df['Age']= df['Age'].replace('Missing',0)
df['Age'] = df['Age'].astype(float)
df['Age'].mean()

In [ ]:
df.dtypes

In [ ]:
df['Salary'] =pd.to_numeric(df['Salary'],errors='coerce')
df['Salary'].mean()

In [ ]:
df.drop(columns='Experience')

In [ ]:
df.drop_duplicates()

In [ ]:
df['Age'].mean().round(2)

In [60]:
# Create a DataFrame from a dictionary.

people = {
    'first_name' : ['bleas','charlie','alies'],
    'last_name': ['doe','kate','john'],
    'email' : ['belas@gmail.com','charlie@gmail.com','alies@gmail.com']
}

df1 = pd.DataFrame(people)
df1

  first_name last_name              email
0      bleas       doe    belas@gmail.com
1    charlie      kate  charlie@gmail.com
2      alies      john    alies@gmail.com

In [63]:
df = pd.read_csv(CSV_PATH)
df

       Name      Age Experience   Salary     Department
0     Belas       23          5    30000             IT
1   Charlie       30          3    35000             HR
2      Kate       25         10    25000   Data Science
3     Alies       32         19    20000      Developer
4     Sunny       29          2    20000          Cloud
5      Paul       20          4    15000        Backend
6     Harsh       21          1    18000             HR
7      Ross      NaN        NaN    40000             IT
8   Missing       32         10    38000   Data Science
9       NaN       24    Missing      NaN  Data Engineer
10     John      NaN          6    28000             IT
11    Sarah       27        NaN  Missing             HR
12      NaN       29          8    32000            NaN
13     Mike  Missing          5    25000      Developer
14    David       26        NaN  Missing          Cloud
15     Emma      NaN        NaN    45000            NaN

In [91]:
df['Salary']=pd.to_numeric(df['Salary'],errors='coerce')
df.loc[df['Salary']>25000]

       Name  Age Experience   Salary    Department
0     Belas   23          5  30000.0            IT
1   Charlie   30          3  35000.0            HR
7      Ross  NaN        NaN  40000.0            IT
8   Missing   32         10  38000.0  Data Science
10     John  NaN          6  28000.0            IT
12      NaN   29          8  32000.0           NaN
15     Emma  NaN        NaN  45000.0           NaN

In [94]:
df['Age']=pd.to_numeric(df['Age'],errors='coerce')
df.loc[df['Age'].between(18,25)]

    Name   Age Experience   Salary     Department
0  Belas  23.0          5  30000.0             IT
2   Kate  25.0         10  25000.0   Data Science
5   Paul  20.0          4  15000.0        Backend
6  Harsh  21.0          1  18000.0             HR
9    NaN  24.0    Missing      NaN  Data Engineer

In [96]:
df.sort_values(by='Salary',ascending=False)

       Name   Age Experience   Salary     Department
15     Emma   NaN        NaN  45000.0            NaN
7      Ross   NaN        NaN  40000.0             IT
8   Missing  32.0         10  38000.0   Data Science
1   Charlie  30.0          3  35000.0             HR
12      NaN  29.0          8  32000.0            NaN
0     Belas  23.0          5  30000.0             IT
10     John   NaN          6  28000.0             IT
2      Kate  25.0         10  25000.0   Data Science
13     Mike   NaN          5  25000.0      Developer
3     Alies  32.0         19  20000.0      Developer
4     Sunny  29.0          2  20000.0          Cloud
6     Harsh  21.0          1  18000.0             HR
5      Paul  20.0          4  15000.0        Backend
9       NaN  24.0    Missing      NaN  Data Engineer
11    Sarah  27.0        NaN      NaN             HR
14    David  26.0        NaN      NaN          Cloud

In [101]:
df.isna().sum()

Name          2
Age           4
Experience    4
Salary        3
Department    2
dtype: int64

In [104]:
df.dropna(inplace=True)

In [108]:
df.fillna(0)

       Name      Age Experience   Salary     Department
0     Belas       23          5    30000             IT
1   Charlie       30          3    35000             HR
2      Kate       25         10    25000   Data Science
3     Alies       32         19    20000      Developer
4     Sunny       29          2    20000          Cloud
5      Paul       20          4    15000        Backend
6     Harsh       21          1    18000             HR
7      Ross        0          0    40000             IT
8   Missing       32         10    38000   Data Science
9         0       24    Missing        0  Data Engineer
10     John        0          6    28000             IT
11    Sarah       27          0  Missing             HR
12        0       29          8    32000              0
13     Mike  Missing          5    25000      Developer
14    David       26          0  Missing          Cloud
15     Emma        0          0    45000              0

In [112]:
df[df.duplicated()]

     Name Age Experience   Salary Department
16  Sarah  27        NaN  Missing         HR

In [123]:
df = df.rename(columns={'Name':'Full Name','Salary':'Monthly_Salary'})
df

   Full Name      Age Experience Monthly_Salary     Department
0      Belas       23          5          30000             IT
1    Charlie       30          3          35000             HR
2       Kate       25         10          25000   Data Science
3      Alies       32         19          20000      Developer
4      Sunny       29          2          20000          Cloud
5       Paul       20          4          15000        Backend
6      Harsh       21          1          18000             HR
7       Ross      NaN        NaN          40000             IT
8    Missing       32         10          38000   Data Science
9        NaN       24    Missing            NaN  Data Engineer
10      John      NaN          6          28000             IT
11     Sarah       27        NaN        Missing             HR
12       NaN       29          8          32000            NaN
13      Mike  Missing          5          25000      Developer
14     David       26        NaN        Missing          Cloud
15      Emma      NaN        NaN          45000            NaN
16     Sarah       27        NaN        Missing             HR

In [135]:
df['Age']=df['Age'].replace('Missing',0)
df['Age'].astype(float)

0     23.0
1     30.0
2     25.0
3     32.0
4     29.0
5     20.0
6     21.0
7      NaN
8     32.0
9     24.0
10     NaN
11    27.0
12    29.0
13     0.0
14    26.0
15     NaN
16    27.0
Name: Age, dtype: float64

In [139]:
# df.drop(columns=['Experience'])
df
# reindex चा वापर करून क्रम बदलणे
# df = df.reindex(columns=['नाव', 'वय', 'पत्ता'])

df.loc[df['Department']=='IT']

   Full Name  Age Experience Monthly_Salary Department
0      Belas   23          5          30000         IT
7       Ross  NaN        NaN          40000         IT
10      John  NaN          6          28000         IT

In [155]:
df[df['Full Name'].str.startswith('B',na=False)]

  Full Name Age Experience Monthly_Salary Department
0     Belas  23          5          30000         IT

In [158]:
df[df['Full Name'].str.contains('an',na=False)]

Empty DataFrame
Columns: [Full Name, Age, Experience, Monthly_Salary, Department]
Index: []

In [160]:
df.loc[(df['Department']=="IT")|(df['Department']=='HR')]

   Full Name  Age Experience Monthly_Salary Department
0      Belas   23          5          30000         IT
1    Charlie   30          3          35000         HR
6      Harsh   21          1          18000         HR
7       Ross  NaN        NaN          40000         IT
10      John  NaN          6          28000         IT
11     Sarah   27        NaN        Missing         HR
16     Sarah   27        NaN        Missing         HR

In [166]:
df.loc[df['Department'].isin(['IT','HR'])]

   Full Name  Age Experience Monthly_Salary Department
0      Belas   23          5          30000         IT
1    Charlie   30          3          35000         HR
6      Harsh   21          1          18000         HR
7       Ross  NaN        NaN          40000         IT
10      John  NaN          6          28000         IT
11     Sarah   27        NaN        Missing         HR
16     Sarah   27        NaN        Missing         HR