In [1]:
import pandas as pd

In [2]:
CSV_PATH = r"C:\Users\Parveen\Desktop\python_projects\python_series\python_practise\data.csv"

df = pd.read_csv(CSV_PATH)
df

,name,age,department,subjects,salary
0,KATE,54,IT,"['OOP', 'DSS', 'RDBMS']",47000
1,JOHN,23,Computer Science,"['Python', 'Java', 'DBMS']",77000
2,ALICE,21,Electronics,"['Digital Logic', 'Microprocessors', 'VLSI']",57000
3,DAVID,22,IT,"['Thermodynamics', 'CAD', 'Fluid Mechanics']",37000

In [ ]:
# give the first 5 rows and if we provide value so it give that range of rows
df.head()
# df.head(10)

In [ ]:
# it give the last 5 rows (default) and if we provide value so it give those rows
df.tail()
# df.tail(10)

In [ ]:
# it give all columns name
df.columns

In [ ]:
# it provide of rows and columns
df.shape

In [ ]:
df.describe()

In [ ]:
df.dtypes

In [ ]:
df.info()

In [ ]:
df["name"]

In [ ]:
df[['name','age']]

In [ ]:
df.loc[0]

In [ ]:
df.iloc[2]

In [ ]:
# slicing using iloc
df.iloc[2:5]

In [ ]:
df.loc[1:5,['name','age']]

In [ ]:
# print how many rows using 3 ways
len(df)
df.index.size
df.shape[0]

In [ ]:
a = [12,3,4,5,6,7,8,9,10]

# formula
# avg = sum(a) / len(a)

avg = df['salary'].mean()
avg

In [ ]:
df.columns.to_list()

df.columns[:4].to_list()

In [ ]:
df.select_dtypes(include='number').columns

In [ ]:
df.loc[df['salary']>90000,['name','salary']]
df

In [ ]:
# & , | operator, ==
# filter > ,<
# df.rename
# str.upper

# all email uppercase using def func
    # using apply

# and condition (want all true = true )
df[(df['salary'] > 90000) & (df['age']>40)]

# or condition (want 1 true)
df[(df['salary'] > 100000) | (df['age']>40)]


# name columns upper case
df['name'].str.upper()

# columns name upper case
df.columns.str.upper().to_list()

# check the name 
df[df['name'] == 'Laurie Cox']

# rename
df.rename(columns={'Unnamed: 0':'Index','name':'Full Name'})

# replace 
df['name'].replace({'Laurie Cox':'Belas'})

In [ ]:
# Create a DataFrame from a CSV file.

people = {
    'first_name' : ['bleas','charlie','alies'],
    'last_name': ['doe','kate','john'],
    'email' : ['belas@gmail.com','charlie@gmail.com','alies@gmail.com']
}


df = pd.DataFrame(people)
df.to_csv('people.csv')

In [ ]:
# Display the first 5 rows.
df.head()

In [ ]:
# Display the last 10 rows.
df.tail(10)

In [ ]:
# Check the number of rows and columns.
df.shape

In [ ]:
# Check column names.
df.columns

In [ ]:
# Check data types of all columns.
df.dtypes

In [ ]:
# Use describe() on numerical columns.
df.describe()

In [ ]:
# Select one column from a DataFrame.
df['name']

In [ ]:
# Select multiple columns.
df[['name','age']]


# iloc on index 
# loc 

# Select rows using iloc.
# Select rows using loc.
df.iloc[0]
df.loc[0]

In [ ]:
# Filter employees whose salary is greater than 50,000.

df.loc[df['salary'] > 50000]

In [ ]:
# Filter students whose age is between 18 and 25.
df.loc[(df['age']>18) & (df['age'] < 25)]

In [ ]:
# Sort a DataFrame by salary in descending order.
df.sort_values(by='salary',ascending=False)

In [ ]:
df.loc[df['age']>25]

In [ ]:
import pandas as pd

In [84]:
CSV_PATH_1 = r"C:\Users\Parveen\Desktop\python_projects\python_series\python_practise\data.csv"
df = pd.read_csv(CSV_PATH_1)
df

,name,age,department,subjects,salary
0,KATE,54,IT,"['OOP', 'DSS', 'RDBMS']",47000
1,JOHN,23,Computer Science,"['Python', 'Java', 'DBMS']",77000
2,ALICE,21,Electronics,"['Digital Logic', 'Microprocessors', 'VLSI']",57000
3,DAVID,22,IT,"['Thermodynamics', 'CAD', 'Fluid Mechanics']",37000

In [ ]:
df[df['department'] == 'IT']

In [85]:
sum(df['salary']) / len(df["salary"])
df["salary"].mean(),

(np.float64(54500.0),)

In [3]:
df.loc[df['salary'] > 50000]

,name,age,department,subjects,salary
1,JOHN,23,Computer Science,"['Python', 'Java', 'DBMS']",77000
2,ALICE,21,Electronics,"['Digital Logic', 'Microprocessors', 'VLSI']",57000

In [11]:
# Filter students whose age is between 18 and 25.
# df.loc[(df['age'] > 18) & (df['age'] < 25)]
df.loc[df['age'].between(18,25)]

,name,age,department,subjects,salary
1,JOHN,23,Computer Science,"['Python', 'Java', 'DBMS']",77000
2,ALICE,21,Electronics,"['Digital Logic', 'Microprocessors', 'VLSI']",57000
3,DAVID,22,IT,"['Thermodynamics', 'CAD', 'Fluid Mechanics']",37000

In [14]:
CSV_FILE = r'./employees.csv'
df = pd.read_csv(CSV_FILE)
df.head()

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,day,temp,condition
0,0,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,3152.00,6304.0,56736.0,0.0,0.0,NaN,NaN,0,NaN
1,1,20,Justin Robinson,43,jadkins@example.com,Civil,97079,East Ericchester,4853.95,9707.9,87371.1,0.0,0.0,NaN,NaN,0,NaN
2,2,10,Mary Hoover,29,khernandez@example.com,Civil,90623,Port Thomasfurt,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
3,3,24,Heather Bailey,23,harrisedward@example.org,Civil,37738,Kristyview,1886.90,3773.8,33964.2,0.0,0.0,NaN,NaN,0,NaN
4,4,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN

In [16]:
df.rename(columns={'name':"Full Name"}).head()

,Unnamed: 0,employee_id,Full Name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,day,temp,condition
0,0,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,3152.00,6304.0,56736.0,0.0,0.0,NaN,NaN,0,NaN
1,1,20,Justin Robinson,43,jadkins@example.com,Civil,97079,East Ericchester,4853.95,9707.9,87371.1,0.0,0.0,NaN,NaN,0,NaN
2,2,10,Mary Hoover,29,khernandez@example.com,Civil,90623,Port Thomasfurt,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
3,3,24,Heather Bailey,23,harrisedward@example.org,Civil,37738,Kristyview,1886.90,3773.8,33964.2,0.0,0.0,NaN,NaN,0,NaN
4,4,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN

In [18]:
df.loc[df['email'] == "terri73@example.org"]

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,day,temp,condition
0,0,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,3152.00,6304.0,56736.0,0.0,0.0,NaN,NaN,0,NaN
4,4,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
22,22,3,Kendra Cunningham,20,terri73@example.org,IT,64085,East Kevintown,0.00,NaN,NaN,0.0,0.0,NaN,NaN,0,NaN
32,32,3,Kendra Cunningham,20,terri73@example.org,IT,64085,East Kevintown,3204.25,6408.5,57676.5,0.0,0.0,NaN,NaN,0,NaN

In [21]:
df['name'].replace({'Laurie Cox':'John doe'})

0              John doe
1       Justin Robinson
2           Mary Hoover
3        Heather Bailey
4              John doe
5           Hannah Reed
6           Craig Lewis
7          Paul Andrews
8           Taylor Kerr
9           Mary Hoover
10       Jared Ferguson
11      Justin Robinson
12          Craig Lewis
13          Taylor Kerr
14       Jared Ferguson
15         Paul Andrews
16       Heather Bailey
17          Hannah Reed
18     Stephanie Murray
19           Todd Clark
20     Stephanie Murray
21           Todd Clark
22    Kendra Cunningham
23        Randall Sharp
24           Sarah Bell
25      Tina Washington
26        Brent Lambert
27      Patricia Hoover
28         Paul Hawkins
29        Randall Sharp
30       Veronica Jones
31       Veronica Jones
32    Kendra Cunningham
33      Patricia Hoover
34        Brent Lambert
35         Paul Hawkins
36      Tina Washington
37           Sarah Bell
38      Charles Wheeler
39       Elizabeth Webb
40          Mark Peters
41        Karen Morales
42         Steven Mason
43        Richard Avila
44           Johnny Roy
45           Johnny Roy
46        Richard Avila
47        Karen Morales
48         Steven Mason
49          Mark Peters
50       Elizabeth Webb
51      Charles Wheeler
52      Rebecca Merritt
53      Rebecca Merritt
54        Frank Johnson
55        Frank Johnson
56      Heather Estrada
57      Heather Estrada
58        Patrick Lewis
59        Patrick Lewis
Name: name, dtype: object

In [24]:
df['yearly_salary'] = df['salary'] * 12
df.head(1)

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,day,temp,condition,yearly_salary
0,0,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,3152.0,6304.0,56736.0,0.0,0.0,NaN,NaN,0,NaN,756480

In [30]:
# df.drop(columns=['day'],inplace=True)
df.head()

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,temp,yearly_salary
0,0,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,3152.00,6304.0,56736.0,0.0,0.0,NaN,0,756480
1,1,20,Justin Robinson,43,jadkins@example.com,Civil,97079,East Ericchester,4853.95,9707.9,87371.1,0.0,0.0,NaN,0,1164948
2,2,10,Mary Hoover,29,khernandez@example.com,Civil,90623,Port Thomasfurt,0.00,NaN,NaN,0.0,0.0,NaN,0,1087476
3,3,24,Heather Bailey,23,harrisedward@example.org,Civil,37738,Kristyview,1886.90,3773.8,33964.2,0.0,0.0,NaN,0,452856
4,4,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,0.00,NaN,NaN,0.0,0.0,NaN,0,756480

In [33]:
df[['first_name','last_name']] = df['name'].str.split(' ',expand=True)
df.head(1)

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,temp,yearly_salary,first_name,last_name
0,0,14,Laurie Cox,22,terri73@example.org,Civil,63040,Jacquelineburgh,3152.0,6304.0,56736.0,0.0,0.0,NaN,0,756480,Laurie,Cox

In [34]:
new_row = pd.DataFrame({
    'name':['Belas Kate'],
    'age':23,
    'salaly':45000
})
df = pd.concat([df,new_row],ignore_index=True)
df

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,temp,yearly_salary,first_name,last_name,salaly
0,0.0,14.0,Laurie Cox,22,terri73@example.org,Civil,63040.0,Jacquelineburgh,3152.00,6304.0,56736.0,0.0,0.0,NaN,0.0,756480.0,Laurie,Cox,NaN
1,1.0,20.0,Justin Robinson,43,jadkins@example.com,Civil,97079.0,East Ericchester,4853.95,9707.9,87371.1,0.0,0.0,NaN,0.0,1164948.0,Justin,Robinson,NaN
2,2.0,10.0,Mary Hoover,29,khernandez@example.com,Civil,90623.0,Port Thomasfurt,0.00,NaN,NaN,0.0,0.0,NaN,0.0,1087476.0,Mary,Hoover,NaN
3,3.0,24.0,Heather Bailey,23,harrisedward@example.org,Civil,37738.0,Kristyview,1886.90,3773.8,33964.2,0.0,0.0,NaN,0.0,452856.0,Heather,Bailey,NaN
4,4.0,14.0,Laurie Cox,22,terri73@example.org,Civil,63040.0,Jacquelineburgh,0.00,NaN,NaN,0.0,0.0,NaN,0.0,756480.0,Laurie,Cox,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,56.0,5.0,Heather Estrada,44,joelho@example.net,Mechanical,76673.0,Micheleshire,3833.65,7667.3,69005.7,0.0,0.0,NaN,0.0,920076.0,Heather,Estrada,NaN
57,57.0,5.0,Heather Estrada,44,joelho@example.net,Mechanical,76673.0,Micheleshire,0.00,NaN,NaN,0.0,0.0,NaN,0.0,920076.0,Heather,Estrada,NaN
58,58.0,29.0,Patrick Lewis,20,tneal@example.org,Mechanical,39095.0,Debbieshire,0.00,NaN,NaN,0.0,0.0,NaN,0.0,469140.0,Patrick,Lewis,NaN
59,59.0,29.0,Patrick Lewis,20,tneal@example.org,Mechanical,39095.0,Debbieshire,1954.75,3909.5,35185.5,0.0,0.0,NaN,0.0,469140.0,Patrick,Lewis,NaN
60,NaN,NaN,Belas Kate,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45000.0

In [39]:
df.sort_values(by='name',ascending=True)
df.sort_values(by='salary',ascending=False)

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,temp,yearly_salary,first_name,last_name,salaly
30,30.0,30.0,Veronica Jones,21,khernandez@example.com,IT,99244.0,North Isaac,4962.20,9924.4,89319.6,0.0,0.0,NaN,0.0,1190928.0,Veronica,Jones,NaN
31,31.0,30.0,Veronica Jones,21,khernandez@example.com,IT,99244.0,North Isaac,0.00,NaN,NaN,0.0,0.0,NaN,0.0,1190928.0,Veronica,Jones,NaN
34,34.0,18.0,Brent Lambert,54,khernandez@example.org,IT,98386.0,West Danielchester,4919.30,9838.6,88547.4,0.0,0.0,NaN,0.0,1180632.0,Brent,Lambert,NaN
26,26.0,18.0,Brent Lambert,54,khernandez@example.org,IT,98386.0,West Danielchester,0.00,NaN,NaN,0.0,0.0,NaN,0.0,1180632.0,Brent,Lambert,NaN
36,36.0,16.0,Tina Washington,22,josephkennedy@example.com,IT,97535.0,Lake Amberfort,4876.75,9753.5,87781.5,0.0,0.0,NaN,0.0,1170420.0,Tina,Washington,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,6.0,7.0,Craig Lewis,22,matthew34@example.net,Civil,34322.0,Christophermouth,0.00,NaN,NaN,0.0,0.0,NaN,0.0,411864.0,Craig,Lewis,NaN
12,12.0,7.0,Craig Lewis,22,matthew34@example.net,Civil,34322.0,Christophermouth,1716.10,3432.2,30889.8,0.0,0.0,NaN,0.0,411864.0,Craig,Lewis,NaN
39,39.0,27.0,Elizabeth Webb,21,josephking@example.com,Marketing,32192.0,Fritzview,0.00,NaN,NaN,0.0,0.0,NaN,0.0,386304.0,Elizabeth,Webb,NaN
50,50.0,27.0,Elizabeth Webb,21,josephking@example.com,Marketing,32192.0,Fritzview,1609.60,3219.2,28972.8,0.0,0.0,NaN,0.0,386304.0,Elizabeth,Webb,NaN
60,NaN,NaN,Belas Kate,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45000.0

In [40]:
df.sort_index()

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,temp,yearly_salary,first_name,last_name,salaly
0,0.0,14.0,Laurie Cox,22,terri73@example.org,Civil,63040.0,Jacquelineburgh,3152.00,6304.0,56736.0,0.0,0.0,NaN,0.0,756480.0,Laurie,Cox,NaN
1,1.0,20.0,Justin Robinson,43,jadkins@example.com,Civil,97079.0,East Ericchester,4853.95,9707.9,87371.1,0.0,0.0,NaN,0.0,1164948.0,Justin,Robinson,NaN
2,2.0,10.0,Mary Hoover,29,khernandez@example.com,Civil,90623.0,Port Thomasfurt,0.00,NaN,NaN,0.0,0.0,NaN,0.0,1087476.0,Mary,Hoover,NaN
3,3.0,24.0,Heather Bailey,23,harrisedward@example.org,Civil,37738.0,Kristyview,1886.90,3773.8,33964.2,0.0,0.0,NaN,0.0,452856.0,Heather,Bailey,NaN
4,4.0,14.0,Laurie Cox,22,terri73@example.org,Civil,63040.0,Jacquelineburgh,0.00,NaN,NaN,0.0,0.0,NaN,0.0,756480.0,Laurie,Cox,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,56.0,5.0,Heather Estrada,44,joelho@example.net,Mechanical,76673.0,Micheleshire,3833.65,7667.3,69005.7,0.0,0.0,NaN,0.0,920076.0,Heather,Estrada,NaN
57,57.0,5.0,Heather Estrada,44,joelho@example.net,Mechanical,76673.0,Micheleshire,0.00,NaN,NaN,0.0,0.0,NaN,0.0,920076.0,Heather,Estrada,NaN
58,58.0,29.0,Patrick Lewis,20,tneal@example.org,Mechanical,39095.0,Debbieshire,0.00,NaN,NaN,0.0,0.0,NaN,0.0,469140.0,Patrick,Lewis,NaN
59,59.0,29.0,Patrick Lewis,20,tneal@example.org,Mechanical,39095.0,Debbieshire,1954.75,3909.5,35185.5,0.0,0.0,NaN,0.0,469140.0,Patrick,Lewis,NaN
60,NaN,NaN,Belas Kate,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45000.0

In [42]:
df.sort_values(by='employee_id',ascending=True)

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,temp,yearly_salary,first_name,last_name,salaly
29,29.0,1.0,Randall Sharp,22,khernandez@example.net,IT,73958.0,Kellymouth,0.00,NaN,NaN,0.0,0.0,NaN,0.0,887496.0,Randall,Sharp,NaN
23,23.0,1.0,Randall Sharp,22,khernandez@example.net,IT,73958.0,Kellymouth,3697.90,7395.8,66562.2,0.0,0.0,NaN,0.0,887496.0,Randall,Sharp,NaN
38,38.0,2.0,Charles Wheeler,30,chad73@example.org,Marketing,81047.0,Robinsonbury,4052.35,8104.7,72942.3,0.0,0.0,NaN,0.0,972564.0,Charles,Wheeler,NaN
51,51.0,2.0,Charles Wheeler,30,chad73@example.org,Marketing,81047.0,Robinsonbury,0.00,NaN,NaN,0.0,0.0,NaN,0.0,972564.0,Charles,Wheeler,NaN
22,22.0,3.0,Kendra Cunningham,20,terri73@example.org,IT,64085.0,East Kevintown,0.00,NaN,NaN,0.0,0.0,NaN,0.0,769020.0,Kendra,Cunningham,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,58.0,29.0,Patrick Lewis,20,tneal@example.org,Mechanical,39095.0,Debbieshire,0.00,NaN,NaN,0.0,0.0,NaN,0.0,469140.0,Patrick,Lewis,NaN
59,59.0,29.0,Patrick Lewis,20,tneal@example.org,Mechanical,39095.0,Debbieshire,1954.75,3909.5,35185.5,0.0,0.0,NaN,0.0,469140.0,Patrick,Lewis,NaN
30,30.0,30.0,Veronica Jones,21,khernandez@example.com,IT,99244.0,North Isaac,4962.20,9924.4,89319.6,0.0,0.0,NaN,0.0,1190928.0,Veronica,Jones,NaN
31,31.0,30.0,Veronica Jones,21,khernandez@example.com,IT,99244.0,North Isaac,0.00,NaN,NaN,0.0,0.0,NaN,0.0,1190928.0,Veronica,Jones,NaN
60,NaN,NaN,Belas Kate,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45000.0

In [46]:
df.sort_values(by='salary',ascending=False).head(1)

,Unnamed: 0,employee_id,name,age,email,department,salary,city,bonus,tax,net_salary,month,sales,subjects,temp,yearly_salary,first_name,last_name,salaly
30,30.0,30.0,Veronica Jones,21,khernandez@example.com,IT,99244.0,North Isaac,4962.2,9924.4,89319.6,0.0,0.0,NaN,0.0,1190928.0,Veronica,Jones,NaN